name: Run lint on any Push event
# Запуск при любом push евенте в любой ветке
on:
  push:
    branches:
      - '*'
jobs:
  run_lint:
    runs-on: kharin
    steps:
    # Устанавливаем python нужной версии
      - name: Install python
        run: apt-get -y install python3.9
      # Чекаутим код
      - uses: actions/checkout@master
      - name: Upgrade pip
        # Устанавливаем зависимости
        run: pip install --upgrade pip
      - name: Install flake8
        run: pip3 install flake8
      - name: Run flake8
        run: flake8 .
