name: Run lint on any Push event
# Запуск при любом push евенте в любой ветке
on:
  push:
    branches:
      - '*'
jobs:
  run_lint:
    # Запускаем джобу на раннере по тегу
    runs-on: ubuntu-latest
    steps:
      # Установка Python 3.9 с помощью actions/setup-python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Чекаут кода
      - uses: actions/checkout@master

      # Обновление pip
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      # Установка flake8
      - name: Install flake8
        run: pip install flake8

      # Запуск flake8
      - name: Run flake8
        run: flake8 .
