name: Run lint on any Push event
# Запуск при любом push евенте в любой ветке
on:
  push:
    branches:
      - '*'
jobs:
  run_lint:
    runs-on: kharin
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Upgrade pip
        # Устанавливаем зависимости
        run: pip install --upgrade pip
      - name: Install flake8
        run: pip3 install flake8
      - name: Run flake8
        run: flake8 .
